language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - sudo apt install libxml2-dev libxslt1-dev python-dev
  - pip install -r requirements.txt

script:
  - pytest test.py
  - coverage run test.py

after_success:
  - coverage report
  - coveralls
